service: future

provider:
  name: aws
  runtime: nodejs8.10
  stage: development
  region: us-east-1
  memorySize: 1024
  timeout: 15
  environment:
    NODE_ENV: production
    LAMBDA: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-plugin-warmup

custom:
  serverless-offline:
    port: 8000
  customDomain:
    domainName: future.huang.mx
    certificateName: '*.huang.mx'
    stage: ${self:provider.stage}
    createRoute53Record: true
  apigwBinary:
    types:
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}
    warmup: true
